### ISSUE TITLE
Creating an instance of a named control without passing an element throws

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-control#54]
If you provide a `name` when extending a control and then create an instance of it without passing an `element`, it will throw when trying to [add a className to the element](https://github.com/canjs/can-control/blob/master/can-control.js#L291).

Here is an example that causes the error:
```
var MyControl = can.Control.extend('MyControl');
new MyControl();
```

and the error:

```
Uncaught TypeError: Cannot read property 'match' of undefined
    at has (http://localhost/nokia-npm/node_modules/can-util/dom/class-name/class-name.js:9:26)
    at add (http://localhost/nokia-npm/node_modules/can-util/dom/class-name/class-name.js:62:17)
    at EPIC_TooltipController.setup (http://localhost/nokia-npm/node_modules/can-control/can-control.js:293:31)
    at Function.newInstance (http://localhost/nokia-npm/node_modules/can-construct/can-construct.js:288:22)
```

**Comment by phillipskevin** [comment]
closed by #55.

**Comment by phillipskevin** [comment]
Instead of creating a `div` to pass to the control, we should just show the dev warning and then return as discussed in https://github.com/canjs/can-control/pull/55#issuecomment-289910585. Also, the tests are failing in IE9: https://github.com/canjs/canjs/pull/3133.

**Comment by phillipskevin** [comment]
closed by https://github.com/canjs/can-control/pull/60.
